"""Add transaction model

Revision ID: 22dba632c03a
Revises: b32f2c9323eb
Create Date: 2026-01-29 09:09:26.728055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dba632c03a'
down_revision: Union[str, Sequence[str], None] = 'b32f2c9323eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_uuid', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('counterparty_name', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('counterparty_account', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_uuid'), 'transactions', ['transaction_uuid'], unique=True)
    op.drop_constraint(op.f('transactions_sender_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'customers', ['customer_id'], ['id'])
    op.drop_column('transactions', 'sender_id')
    op.drop_column('transactions', 'transaction_id')
    op.drop_column('transactions', 'receiver_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver_account', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_sender_id_fkey'), 'transactions', 'customers', ['sender_id'], ['id'])
    op.drop_index(op.f('ix_transactions_transaction_uuid'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('transactions', 'risk_score')
    op.drop_column('transactions', 'customer_id')
    op.drop_column('transactions', 'counterparty_account')
    op.drop_column('transactions', 'counterparty_name')
    op.drop_column('transactions', 'transaction_uuid')
    # ### end Alembic commands ###
